qnt_umreal = int(input("quantidade de moedas de um real"))
qnt_50cent = float(input("quantidade de moedas de 50 centavos"))
qnt_25cent = float(input("quantidade de moedas de 25 centavos"))
valor_total = (qnt_umreal*1)+(qnt_50cent*0.5)+(qnt_25cent*0.25)
print("O valor total é de: {valor_total}")